config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  
  resources :users, only: [:new, :create, :show]

  resources :users do
    resources :colors, only: [:new, :create, :edit, :update, :destroy]
    resources :reactions, only: [:new, :create, :edit, :update, :destroy]
  end

  namespace :admin do
    resources :surveys, only: [:index, :edit, :create, :destroy]
  end

  resources :colors do 
    resources :surveys, only: [:new, :create]
  end
  
  resources :colors , only: [:index, :show]
  resources :reactions, only: [:index, :show]
 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/color.rb
class Color < ApplicationRecord
  validates_presence_of :name, :user_id
  validates :hex_value, presence: true, uniqueness: { case_sensitive: false }

  belongs_to :user
  has_many :surveys, dependent: :destroy
  has_many :reactions, through: :surveys

  def self.pick_two
    Color.order('RANDOM()').limit(2)
  end
end

app/models/reaction.rb
class Reaction < ApplicationRecord
  validates_presence_of :definition, :user_id
  validates :word, presence: true, uniqueness: { case_sensitive: false }

  belongs_to :user
  has_many :surveys, dependent: :destroy
  has_many :colors, through: :surveys
end

app/models/session.rb
class Session < ApplicationRecord
  validates_presence_of :color_id, :reaction_id
  belongs_to :color
  belongs_to :reaction
end

app/models/survey.rb
class Survey < ApplicationRecord
  validates_presence_of :color_id, :reaction_id, :user_id
  belongs_to :color
  belongs_to :reaction
  belongs_to :user

  def self.sort_by_color(color)
    where(color: color)
  end

  def self.sort_by_reaction(reaction)
    where(reaction: reaction)
  end
end

app/models/user.rb
class User < ApplicationRecord
  validates :email, uniqueness: true, presence: true
  validates_presence_of :name, require: true
  validates_presence_of :password, require: true

  has_secure_password

  enum role: ['default', 'admin']

  has_many :colors
  has_many :reactions
  has_many :surveys
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
  before_action :require_admin

  private

  def require_admin
    render file:'/public/404' unless current_admin?
  end
end

app/controllers/admin/surveys_controller.rb
class Admin::SurveysController < Admin::BaseController
  
  def index
    @surveys = Survey.all
  end

  def destroy
    Survey.destroy(params[:id])
    redirect_to admin_surveys_path
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user, :current_admin?, :two_colors

  def current_user
    if session[:user_id]
      @current_user ||= User.find(session[:user_id])
    end
  end

  def current_admin?
    current_user && current_user.admin?
  end

  def two_colors
    @two_colors = Color.pick_two
  end
end

app/controllers/colors_controller.rb
class ColorsController < ApplicationController
  before_action :two_colors

  def index
    @colors = Color.all
  end
  
  def show
    @color = Color.includes(:reactions).find(params[:id])
    @reactions = Reaction.all
    @survey = Survey.new
  end

  def new
    @user = User.find(params[:user_id])
    @color = Color.new
  end

  def create
    @user = User.find(params[:user_id])
    @color = @user.colors.create(color_params)
    if @color.save
      redirect_to color_path(@color)
      flash.notice = "#{@color.name} has been added to chromotherapy."
    else
      render :new
    end
  end

  def edit
    @color = Color.find(params[:id])
  end

  def update
    @color = Color.find(params[:id])
    @color.update(color_params)
    if @color.save
      redirect_to color_path(@color)
      flash.notice = "#{@color.name} has been updated."
    else
      flash.notice = "Colors cannot be duplicated."
      render :edit
    end
  end

  def destroy
    color = Color.find(params[:id])
    color.destroy
    if current_admin?
      redirect_to colors_path
    else
    redirect_to user_path(current_user)
    end
    flash.notice = "#{color.name} has been removed from chromotherapy"
  end

  private 
  
  def color_params
    params.require(:color).permit(:name, :hex_value)
  end

end

app/controllers/reactions_controller.rb
class ReactionsController < ApplicationController
  before_action :current_admin?,  only: [:new, :create, :edit, :update, :destroy]
  before_action :two_colors
  
  def index
    @reactions = Reaction.all
  end

  def show
    @reaction = Reaction.includes(:colors).find(params[:id])
  end

  def new
    @reaction = Reaction.new
  end

  def create
    @reaction = current_user.reactions.create!(reaction_params)
    if @reaction.save
      redirect_to reaction_path(@reaction)
      flash.notice = "#{@reaction.word} has been added to chromotherapy."
    else
      render :new
    end
  end

  def edit
    @reaction = Reaction.find(params[:id])
  end

  def update
    @reaction = Reaction.find(params[:id])
    @reaction.update(reaction_params)
    if @reaction.save
      redirect_to reaction_path(@reaction)
      flash.notice = "Reaction has been updated."
    else
      flash.notice = "Reactions cannot be duplicated."
      render :edit
    end
  end

  def destroy
    reaction = Reaction.find(params[:id])
    reaction.destroy
    if current_admin?
      redirect_to reactions_path
    else
      redirect_to user_path(current_user)
    end
    flash.notice = "#{reaction.word} has been removed chromotherapy"
  end

  private 

  def reaction_params
    params.require(:reaction).permit(:word, :definition)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :two_colors
  
  def new
  end

  def create
    @user = User.find_by_email(params[:email])
    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/surveys_controller.rb
class SurveysController < ApplicationController
  def new
    @survey = Survey.new
    @color = Color.find(params[:color_id])
  end

  def create
    @color = Color.find(params[:color_id])
    @survey = @color.surveys.create!(survey_params)
    redirect_to color_path(@color)
  end

  private

  def survey_params
    params.require(:survey).permit(:reaction_id, :user_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :two_colors
  
  def show
    @user = User.includes(:colors, :reactions, :surveys).find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :name, :password)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  before_action :two_colors
  
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/surveys/index.html.erb
  <div class="container">
      <div class="columns\">
        <section class="column">
          <h1 class="title is-4"> All Chromotherapy Surveys</h1>
          <h2 class="sube-title"><%= @surveys.length %> in the Database</h2>
        </section>
        <section class="column">
          <table class="table">
            <tr>
              <th>User</th>
              <th>Color</th>
              <th>Reaction</th>
            </tr>
              <% @surveys.each do |survey| %>
                <tr id="survey-<%= survey.id %>">
                  <td><%= link_to survey.user.name, user_path(survey.user)%></td>
                  <td bgcolor="<%= survey.color.hex_value%>"><%= link_to survey.color.name, color_path(survey.color) %></td>
                  <td><%= link_to survey.reaction.word, reaction_path(survey.reaction) %></td>
                  <td><%= link_to 'delete', admin_survey_path(survey), method: 'DELETE', data: {confirm: "Really delete survey?"} %></td>
                </tr>
              <% end %>
          </table>
        </section>
      </div>
  </div>

app/views/colors/_admin_index.html.erb
<div class="container">
  <div class="columns is-multiline">
    <div class="column">
      <h1 class"sub-title">
        <%= link_to 'add color to database', new_user_color_path(current_user), method: 'GET' %>
      </h1>
      <table class="table">
        <th>Color</th>
        <th>Hex Value</th>
        <% @colors.each do |color| %>
        <tr id="color-<%= color.id %>">
          <td><%= link_to  color.name, color_path(color) %></td>
          <td bgcolor="<%= color.hex_value %>" class="has-text-white"><%= color.hex_value %></td>
          <td><%= link_to 'delete', user_color_path(color.user, color), method: 'DELETE', data: {confirm: "Really delete #{color.name}"} %></td>
          <td><%= link_to 'edit', edit_user_color_path(color.user, color), method: 'GET' %></td>
        </tr>
        <% end %>
      </table>
    </div>
  </div>  
</div>  

app/views/colors/_box.html.erb
<script type="text/javascript">

    function full_screen()
    {
        // check if user allows full screen of elements. This can be enabled or disabled in browser config. By default its enabled.
        //its also used to check if browser supports full screen api.
        if("fullscreenEnabled" in document || "webkitFullscreenEnabled" in document || "mozFullScreenEnabled" in document || "msFullscreenEnabled" in document)
        {
            if(document.fullscreenEnabled || document.webkitFullscreenEnabled || document.mozFullScreenEnabled || document.msFullscreenEnabled)
            {
                console.log("User allows fullscreen");
            
                var element = document.getElementById("color-box");
                //requestFullscreen is used to display an element in full screen mode.
                if("requestFullscreen" in element)
                {
                    element.requestFullscreen();
                }
                else if ("webkitRequestFullscreen" in element)
                {
                    element.webkitRequestFullscreen();
                }
                else if ("mozRequestFullScreen" in element)
                {
                    element.mozRequestFullScreen();
                }
                else if ("msRequestFullscreen" in element)
                {
                    element.msRequestFullscreen();
                }

            }
        }
        else
        {
            console.log("User doesn't allow full screen");
        }
    }

    function screen_change()
    {
        //fullscreenElement is assigned to html element if any element is in full screen mode.
        if(document.fullscreenElement || document.webkitFullscreenElement || document.mozFullScreenElement || document.msFullscreenElement)
        {
            console.log("Current full screen element is : " + (document.fullscreenElement || document.webkitFullscreenElement || document.mozFullScreenElement || document.msFullscreenElement))
        }
        else
        {
            // exitFullscreen us used to exit full screen manually
            if ("exitFullscreen" in document)
            {
                document.exitFullscreen();
            }
            else if ("webkitExitFullscreen" in document)
            {
                document.webkitExitFullscreen();
            }
            else if ("mozCancelFullScreen" in document)
            {
                document.mozCancelFullScreen();
            }
            else if ("msExitFullscreen" in document)
            {
                document.msExitFullscreen();
            }
        }
    }

    //called when an event goes full screen and vice-versa.
    document.addEventListener("fullscreenchange", screen_change);
    document.addEventListener("webkitfullscreenchange", screen_change);
    document.addEventListener("mozfullscreenchange", screen_change);
    document.addEventListener("MSFullscreenChange", screen_change);

    //called when requestFullscreen(); fails. it may fail if iframe don't have allowfullscreen attribute enabled or for something else.
    document.addEventListener("fullscreenerror", function(){console.log("Full screen failed");});
    document.addEventListener("webkitfullscreenerror", function(){console.log("Full screen failed");});
    document.addEventListener("mozfullscreenerror", function(){console.log("Full screen failed");});
    document.addEventListener("MSFullscreenError", function(){console.log("Full screen failed");});
</script>
<style type="text/css">
    #color-box
    {
        height: 300px;
        width: 300px;
        background-color: <%= @color.hex_value %>;
    }

    #color-box:-webkit-full-screen
    {
        background-color: <%= @color.hex_value %>;
    }
        
    #color-box:-moz-full-screen
    {
        background-color: <%= @color.hex_value %>;
    }
        
    #color-box:-ms-fullscreen
    {
        background-color: <%= @color.hex_value %>;
    }
        
    #color-box:fullscreen
    {
        background-color: <%= @color.hex_value %>;
    }

    /*backdrop pseudo element is used to style element behing the full screen element.*/
    :fullscreen::backdrop
    {
        background-color: red;
    }

    :-webkit-full-screen::-webkit-backdrop
    {
        background-color: red;
    }
    
    :-moz-full-screen::-moz-backdrop {
        background-color: red;
    }

    :-ms-fullscreen::-ms-backdrop {
        background-color: red; /* dark blue */
    }

</style>

<div id="color-box" onclick="full_screen();"></div>

app/views/colors/_form.html.erb
<style>
#grad {
  background: linear-gradient(to bottom right, <%= @two_colors[0].hex_value %>, <%= @two_colors[1].hex_value %>);
}
</style>
<section id="grad" class="hero is-white is-fullheight">
        <div class="hero-body">
            <div class="container has-text-centered">
                <div class="column is-4 is-offset-4">
                    <h3 class="title has-text-white">Please enter the name of the Color and its Hexadecimal value starting with '#'</h3>
                    <p class="subtitle has-text-white">Need help deciding? <a href="https://htmlcolorcodes.com/color-picker/" target="_blank">Try this color picker</a> by <a href="https://dixonandmoe.com/" target="_blank">Dixon & Moe</a></p>
                    <div class="box">
                        <%= form_for [current_user, @color] do |f| %>
                            <div class="field">
                                <div class="control">
                                  <%=f.label :name%>
                                  <%= f.text_field :name, class: "input is-large",placeholder: "Color's Name"  %>
                                </div>
                            </div>
                            <div class="field">
                                <div class="control">
                                  <%=f.label :hex_value%>
                                  <%= f.text_field :hex_value, class: "input is-large", placeholder: "#000000"  %>
                                </div>
                            </div>
                            <%= f.submit class: "button is-block is-info is-large is-fullwidth" %>
                        <% end %>
                    </div>
                </div>
            </div>
        </div>
    </section>
<script async type="text/javascript" src="../js/bulma.js"></script>

app/views/colors/_index.html.erb
<div class="container">
    <div class="columns is-multiline">
      <% @colors.each do |color| %>
        <%= link_to color_path(color) do %>
          <div class="column" id="color-<%= color.id %>"=>
              <style>
              #color-<%= color.id %> {color: <%= color.hex_value %>;
                                      background-color: <%= color.hex_value %>;
                                      height: 300px;
                                      width: 300px;}
              </style>
              <p><%= color.name %></p>
          </div>
        <% end %>
    <% end %>
  </div>
</div>

app/views/colors/index.html.erb
  <% if current_admin? %>
    <%= render partial: 'admin_index' %>
  <% else %>
    <%= render partial: 'index' %>
  <% end %>

app/views/colors/show.html.erb
<section class="hero is-white is-fullheight">
  <div class="hero-body">
      <div class="container">
        <div class="columns is-multiline">
          <section class="column is-6 is-offset-4">
            <h1 class="title"><%= @color.name %></h1>
            <p class="sub-title"><%= @color.hex_value %></p>
            <p class="subtitle">added by: <%= link_to @color.user.name, user_path(@color.user) %></p>
          </section>
          <section class="column is-4 is-offset-4">
            <%= render partial: 'box'%>
          </section>

          <section class="column is-4 is-offset-2">
            <h1>Reactions</h1>
            <table class="table">
              <tr>
                <th>Word</th>
                <th>Definition</th>
              </tr>
              <% @color.reactions.distinct.each do |reaction| %>
              <tr id="reaction-<%= reaction.id %>">
                <td><%= link_to reaction.word, reaction_path(reaction)%></td>
                <td><%= reaction.definition%></td>
              </tr>
              <% end %>
            </table>
          </section>
          <section class="column is-4">
          <% if current_user %>
            <%= render partial: '/surveys/form' %>
          <% else %>
            <h1 class="title is-6">
              You need to be a registered user to log a reaction.
            </h1>
            <%= link_to 'sign up', new_user_path, class: 'link' %>
          <% end %>
          </section>
        </div>
      </div>
    </div>
</section>

app/views/layouts/_nav.html.erb
<nav class="navbar">
  <div class="container">
    <div class="navbar-brand">
      <a class="navbar-item" href="<%= root_path %>" style="font-weight:bold;">
      Chromotherapy
      </a>
      <span class="navbar-burger burger" data-target="navMenu">
        <span></span>
        <span></span>
        <span></span>
      </span>
    </div>
    <div id="navMenu" class="navbar-menu">
      <div class="navbar-start">
        <%= link_to 'Colors', colors_path, class: 'navbar-item' %>
        <%= link_to 'Reactions', reactions_path, class: 'navbar-item' %>
        <% if current_admin? %>
          <%= link_to 'Surveys', admin_surveys_path, class: 'navbar-item' %>
        <% end %>
      </div>
      <div class="navbar-end">
        <% if current_user %>
          <%= link_to 'my profile', user_path(current_user), class: 'navbar-item' %>
          <%= link_to 'log out', logout_path, class: 'navbar-item'%>
        <% else%>
          <%= link_to 'sign up', new_user_path, class: 'navbar-item'%>
          <%= link_to 'log in', login_path, class: 'navbar-item'%>
        <% end %>
      </div>
    </div>
  </div>
</nav>
<script type="text/javascript">
(function() {
  var burger = document.querySelector('.burger');
  var nav = document.querySelector('#'+burger.dataset.target);
 
  burger.addEventListener('click', function(){
    burger.classList.toggle('is-active');
    nav.classList.toggle('is-active');
  });
})();
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Chromotherapy</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>
  <body>
    <%= render partial: '/layouts/nav' %>
    <%= yield %>
  </body>
</html>

app/views/reactions/_form.html.erb
<style>
#grad {
  background: linear-gradient(to bottom right, <%= @two_colors[0].hex_value %>, <%= @two_colors[1].hex_value %>);
}
</style>

<section id="grad" class="hero is-white is-fullheight">
        <div class="hero-body">
            <div class="container has-text-centered">
                <div class="column is-4 is-offset-4">
                    <h3 class="title has-text-white">Please enter a word and its definition.</h3>
                    <div class="box">
                        <%= form_for [current_user, @reaction] do |f| %>
                            <div class="field">
                                <div class="control">
                                  <%=f.label :word%>
                                  <%= f.text_field :word, class: "input is-large",placeholder: "Word"  %>
                                </div>
                            </div>
                            <div class="field">
                                <div class="control">
                                  <%=f.label :definition%>
                                  <%= f.text_field :definition, class: "input is-large", placeholder: "Definition"  %>
                                </div>
                            </div>
                            <%= f.submit class: "button is-block is-info is-large is-fullwidth" %>
                        <% end %>
                    </div>
                </div>
            </div>
        </div>
    </section>
<script async type="text/javascript" src="../js/bulma.js"></script>

app/views/reactions/edit.html.erb
<section>
  <%= render 'form' %>
</section>

app/views/reactions/index.html.erb
  <div class="container">
      <div class="columns is-multiline">
        <% if current_admin? %>
          <div class="column">
            <h1 class"sub-title">
              <%= link_to 'add reaction to database', new_user_reaction_path(current_user), method: 'GET' %>
            </h1>
          </div>
        <% end %>
        <% @reactions.each do |reaction| %>
          <%= link_to reaction_path(reaction) do %>
          <div class="column box has-text-centered" id="reaction-<%= reaction.id %>"=>
            <p class="title"><%= reaction.word %></p>
            <p class="sub-title"><%= reaction.definition %></p>
             <% if current_admin? %>
              <%= link_to 'delete', user_reaction_path(reaction.user, reaction), method: 'DELETE', data: {confirm: "Really delete #{reaction.word}"} %>
              <%= link_to 'edit', edit_user_reaction_path(reaction.user, reaction), method: 'GET' %>
            <% end %>
          </div>
          <% end %>
     <% end %>
      </div>
  </div>

app/views/reactions/new.html.erb
<section>
  <%= render 'form' %>
</section>

app/views/reactions/show.html.erb
<section class="hero is-white is-fullheight">
  <div class="hero-body">
      <div class="container">
        <div class="columns">
          <section class="column">
            <h1 class="title"><%= @reaction.word %></h1>
            <h1 class="sub-title"><%= @reaction.definition%></h1>
          </section>

          <section class="column">
            <table class="table">
              <th>Colors associated with <%= @reaction.word %></th>
              <% @reaction.colors.each do |color| %>
                <tr>
                  <td bgcolor="<%=color.hex_value%>" class="has-text-white"><%= link_to color.name, color_path(color) %></td>
                </tr>
              <% end %>
            </table>
          </section>
          
        </div>
      </div>
    </div>
</section>

app/views/surveys/_form.html.erb
<h1 class="title">Submit your reaction here</h1>
<p class="sub-title">
Instructions:
<ol>
<li>Click on the color square to view the color in fullscreen.</li>
<li>Position yourself or the screen you are using so that the color field fills your vision.</li>
<li>Let your eyes relax and lose focus.</li>
<li>Stare into the color.</li>
<li>When you feel that you have had enough time with the color, press the escape key to exit fullscreen.</li>
<li>Choose the reaction you feel most appropriate from the drop-down menu and press 'submit'.</li>
</p>
<br>
<%= form_for [@color, @survey] do |f| %>

  <%= f.label :reaction_id %>
  <%= f.collection_select :reaction_id, @reactions,:id,:word, include_blank: true %>
  <%= f.hidden_field :user_id, value: current_user.id %>
  <%= f.submit 'submit'%>
<% end %>

app/views/users/show.html.erb
<section class="hero is-small">
  <div class="hero-body">
    <div class="container has-text-centered">
        <% if current_user && current_user.id == @user.id %>
          <h1 class="title">
          Welcome, <%=@user.name%>!
          </h1>
          <h2 class="subtitle">
          From here you can view colors, reactions and surveys you have added to the database.<br>
          and you can <%= link_to 'Add a color to the Chromotherapy database', new_user_color_path(@user) %>
          or
          <%= link_to 'Add a reaction to the Chromotherapy database', new_user_reaction_path(@user) %>
          </h2>
        <%else%>
          <h1 class="title">
          <%=@user.name%>'s profile
          </h1>
        <%end%>
    </div>
  </div>
</section>

<div class="columns is-multiline">
  <section class="column is-offset-1">
      <h1>Colors Added by <%= @user.name %>
      <table class="table">
        <tr>
          <th>Name</th>
          <th>Hex Value</th>
        </tr>
      <% @user.colors.each do |color| %>
        <tr id="color-<%= color.id %>">
          <td><%= link_to color.name, color_path(color)%></td>
          <td bgcolor="<%= color.hex_value%>"><%= color.hex_value %></td>
          <% if current_user && current_user.id == @user.id %>
            <td><%= link_to 'delete', user_color_path(@user, color), method: 'DELETE', data: {confirm: "Really delete #{color.name}"} %></td>
            <td><%= link_to 'edit', edit_user_color_path(@user, color), method: 'GET' %></td>
          <% end %>
        </tr>
      <% end %>
      </table>
    </section>

  <section class="column">
      <h1>Your Color Surveys</h1>
      <table class="table">
        <tr>
          <th>Color</th>
          <th>Reaction</th>
        </tr>
      <% @user.surveys.each do |survey| %>
        <tr id="survey-<%= survey.id %>">
          <td><%= survey.color.name%></td>
          <td><%= survey.reaction.word%></td>
        </tr>
      <% end %>
      </table>
    </section>

    <section class="column">
      <h1>Reactions Added by <%= @user.name %>
      <table class="table">
        <tr>
          <th>Word</th>
          <th>Definition</th>
        </tr>
      <% @user.reactions.each do |reaction| %>
        <tr id="reaction-<%= reaction.id %>">
          <td><%= link_to reaction.word, reaction_path(reaction)%></td>
          <td><%= reaction.definition%></td>
          <% if current_user && current_user.id == @user.id %>
            <td><%= link_to 'delete', user_reaction_path(@user, reaction), method: 'DELETE'%></td>
            <td><%= link_to 'edit', edit_user_reaction_path(@user, reaction), method: 'GET' %></td>
          <% end %>
        </tr>
      <% end %>
      </table>
    </section>
    <section class="column is-1">
    </section>
  </div>

app/views/welcome/index.html.erb
 <style>
#grad {
  background: linear-gradient(to bottom right, <%= @two_colors[0].hex_value %>, <%= @two_colors[1].hex_value %>);
}
</style>
 <body>
        <section id= "grad" class="hero is-medium">
            <div class="hero-head">
      
            </div>
            <div class="hero-body">
                <div class="container has-text-centered">
                    <h1 class="title has-text-white">
                    Chromotherapy
                    </h1>
                    <h2 class="subtitle has-text-white">
                    This website was created to log people's emotional reactions to particular colors.
                    </h2>
                </div>
            </div>
        </section>
        <div class="box cta">
            <p class="has-text-centered">
              To add colors to the database and log your reactions, please <%= link_to 'sign up', new_user_path %>
            </p>
        </div>
        <section class="container">
            <div class="columns features">
                <div class="column is-4 is-offset-2">
                    <div class="card is-shady">
                        <div class="card-image has-text-centered">
                            <i class="fa fa-paw"></i>
                        </div>
                        <div class="card-content">
                            <div class="content">
                                <h4>Chromotherapy background </h4>
                                <p>Chromotherapy, sometimes called color therapy, colorology or cromatherapy, is an alternative medicine method, which is considered pseudoscience.[1] Chromotherapists claim to be able to use light in the form of color to balance "energy" lacking from a person's body, whether it be on physical, emotional, spiritual, or mental levels. </p>
                                <p><a href="https://en.wikipedia.org/wiki/Chromotherapy" target="_blank">Learn more</a></p>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="column is-4">
                    <div class="card is-shady">
                        <div class="card-image has-text-centered">
                            <i class="fa fa-empire"></i>
                        </div>
                        <div class="card-content">
                            <div class="content">
                                <h4>About this site</h4>
                                <p>This site is meant to gather simple information about how a user feels while observing colors. Over time, with enough use, it will provide a large data pool to aid in understanding our interaction with visual stimulus. Once you are logged in, you can find instruction on how to log your reaction on each color's page. Once you have an account you can view your profile to revisit which colors you have experienced.</p>
                                <p><a href="https://github.com/jtrtj/chromotherapy" target="_blank">View on GitHub</a></p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            </div>
            <script src="../js/bulma.js"></script>
</footer>